export const activities = [
  {
    activity: 'Swimming in the Fox Glacier',
    startDate: '2020-04-04',
    endDate: '2020-04-04',
    startTime: '05:30',
    finishTime: '06:30',
    location: 'Fox Glacier',
    notes: 'Bring your wet suit, its gonna be cold',
  },
  {
    activity: 'Climbing Mount Cook',
    startDate: '2020-04-05',
    endDate: '2020-04-05',
    startTime: '10:30',
    finishTime: '15:30',
    location: 'Mount Cook',
    notes: 'Bring junk foods',
  },
  {
    activity: 'Having dinner in the Moon restaurant at the top of Mount Cook',
    startDate: '2020-04-05',
    endDate: '2020-04-05',
    startTime: '17:30',
    finishTime: '20:30',
    location: 'Moon restaurant',
    notes:
      'It is not going to be a cheap dinner so please bring a thick wallet',
  },
  {
    activity: 'Sleeping at Mount Cook Lodge',
    startDate: '2020-04-05',
    endDate: '2020-04-06',
    startTime: '21:30',
    finishTime: '08:30',
    location: 'Mount Cook lodge',
    notes: 'Nice and warm place to rest after a long day',
  },
  {
    activity: 'Descending Mount Cook',
    startDate: '2020-04-06',
    endDate: '2020-04-06',
    startTime: '10:30',
    finishTime: '15:30',
    location: 'Top of Mount Cook',
    notes: 'Its gonna be an easy trip',
  },
];
